# Generated by Django 3.2.4 on 2021-06-16 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_auto_20210614_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'Actor', 'verbose_name_plural': 'Actors'},
        ),
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name': 'Director', 'verbose_name_plural': 'Directors'},
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'verbose_name': 'Film', 'verbose_name_plural': 'Films'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'genre', 'verbose_name_plural': 'genres'},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'verbose_name': 'Score', 'verbose_name_plural': 'Scores'},
        ),
        migrations.RemoveField(
            model_name='film',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='film',
            name='scores',
        ),
        migrations.AddField(
            model_name='score',
            name='film',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='films.film'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(null=True, related_name='films', to='films.Actor', verbose_name='actors'),
        ),
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.TextField(max_length=5000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='film',
            name='directors',
            field=models.ManyToManyField(null=True, related_name='films', to='films.Director', verbose_name='directors'),
        ),
        migrations.AlterField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(null=True, related_name='films', to='films.Genre', verbose_name='genre'),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=5000, verbose_name='text')),
                ('film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='films.film', verbose_name='film')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
